### ISSUE TITLE
I can't work with open telemetry collector

### ISSUE THREAD

**Issue by sabexzero** [sabexzero/shuttle-microservices#8]
**I am deploying the opentelemetry collector with the standard configuration:**
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        
processors:
  batch:

exporters:
  logging:
  prometheus:
    endpoint: "0.0.0.0:9999"  

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
```

**The configuration of the open telemetry client for each microservice is as follows::**
```yaml
spring:
    opentelemetry:
      traces:
        exporter:
          otlp:
            endpoint: http://localhost:4317
        sampler:
          probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
```

**However, I get this error even though I disable grpc and use http only:**

```
2024-07-12T23:27:06.809+03:00  WARN 26632 --- [user-feedback-service] [lector:4317/...] i.o.exporter.internal.grpc.GrpcExporter  : Failed to export spans. Server responded with gRPC status code 2. Error message: otel-collector
```
